import type { Developer, College, Community, Organization, Hackathon, DevRankBadge, Insight, GitHubStats } from "./types";

const A = "https://api.dicebear.com/7.x/avataaars/svg?seed=";

export const DEVELOPERS: Developer[] = [
  { id: "d1", username: "alexchen", displayName: "Alex Chen", avatar: A+"Alex", bio: "Full-stack developer & open source enthusiast. Building the future of web.", college: "MIT", community: "MLSA", organization: "Google", country: "USA", city: "Cambridge", rank: 1, score: 9850, tier: "Elite", prs: 342, mergedPrs: 298, stars: 15200, followers: 8430, commits: 2840, repos: 87, issues: 156, reviews: 423, streak: 45, languages: ["TypeScript", "Rust", "Python", "Go"], techStack: ["React", "Next.js", "Turborepo", "Kubernetes"], badges: ["top-contributor", "open-source-champion", "ai-builder"], achievements: ["1000 Stars", "500 PRs", "Top 10"], contributionHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 20)), joinedAt: "2020-03-15" },
  { id: "d2", username: "sarahjohnson", displayName: "Sarah Johnson", avatar: A+"Sarah", bio: "AI/ML researcher and Rustacean. Contributing to compiler tooling.", college: "Stanford", community: "GDSC", organization: "Meta", country: "USA", city: "Palo Alto", rank: 2, score: 8720, tier: "Elite", prs: 289, mergedPrs: 245, stars: 12800, followers: 7210, commits: 2450, repos: 64, issues: 132, reviews: 356, streak: 38, languages: ["Rust", "Python", "C++", "TypeScript"], techStack: ["PyTorch", "Rustc", "LLVM", "React"], badges: ["open-source-champion", "ai-builder", "rising-star"], achievements: ["500 Stars", "200 PRs", "Top Contributor"], contributionHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 18)), joinedAt: "2019-08-22" },
  { id: "d3", username: "priyasharma", displayName: "Priya Sharma", avatar: A+"Priya", bio: "Distributed systems engineer. Apache committer & K8s contributor.", college: "IIT Bombay", community: "AWS User Group", organization: "Amazon", country: "India", city: "Mumbai", rank: 3, score: 7650, tier: "Elite", prs: 256, mergedPrs: 212, stars: 9800, followers: 5640, commits: 2100, repos: 52, issues: 98, reviews: 287, streak: 32, languages: ["Go", "Java", "Python", "Rust"], techStack: ["Kubernetes", "Terraform", "Apache Kafka", "Docker"], badges: ["top-contributor", "elite-contributor", "community-leader"], achievements: ["1000 Stars", "Apache Committer"], contributionHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 22)), joinedAt: "2018-11-05" },
  { id: "d4", username: "mikerodriguez", displayName: "Mike Rodriguez", avatar: A+"Mike", bio: "Frontend architect & design systems engineer.", college: "MIT", community: "Developer", organization: "Vercel", country: "USA", city: "San Francisco", rank: 4, score: 6540, tier: "Diamond", prs: 234, mergedPrs: 195, stars: 8900, followers: 4320, commits: 1890, repos: 45, issues: 87, reviews: 234, streak: 28, languages: ["TypeScript", "CSS", "JavaScript", "Swift"], techStack: ["React", "Next.js", "Tailwind", "Radix UI"], badges: ["full-stack-dev", "top-contributor"], achievements: ["500 Stars", "Community Leader"], contributionHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 15)), joinedAt: "2021-01-10" },
  { id: "d5", username: "emmawilson", displayName: "Emma Wilson", avatar: A+"Emma", bio: "DevOps & cloud infrastructure specialist.", college: "UBC", community: "AWS User Group", organization: "Netflix", country: "Canada", city: "Vancouver", rank: 5, score: 5890, tier: "Diamond", prs: 198, mergedPrs: 167, stars: 7200, followers: 3510, commits: 1650, repos: 38, issues: 72, reviews: 198, streak: 24, languages: ["Go", "Python", "HCL", "Shell"], techStack: ["AWS", "Terraform", "Docker", "Prometheus"], badges: ["open-source-champion", "community-leader"], achievements: ["500 Stars", "DevOps Expert"], contributionHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 16)), joinedAt: "2019-05-18" },
  { id: "d6", username: "davidkim", displayName: "David Kim", avatar: A+"David", bio: "Systems programmer & database internals enthusiast.", college: "KAIST", community: "GDSC", organization: "Oracle", country: "South Korea", city: "Seoul", rank: 6, score: 5210, tier: "Platinum", prs: 176, mergedPrs: 145, stars: 5600, followers: 2840, commits: 1420, repos: 32, issues: 63, reviews: 165, streak: 20, languages: ["Rust", "C", "C++", "Java"], techStack: ["Linux", "PostgreSQL", "Redis", "gRPC"], badges: ["ai-builder", "rising-star"], achievements: ["250 Stars"], contributionHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 14)), joinedAt: "2020-07-22" },
  { id: "d7", username: "lisathompson", displayName: "Lisa Thompson", avatar: A+"Lisa", bio: "Mobile developer & Flutter contributor.", college: "UNSW", community: "GDG", organization: "Canva", country: "Australia", city: "Sydney", rank: 7, score: 4780, tier: "Platinum", prs: 156, mergedPrs: 128, stars: 4200, followers: 2150, commits: 1250, repos: 28, issues: 54, reviews: 143, streak: 17, languages: ["Dart", "Kotlin", "Swift", "TypeScript"], techStack: ["Flutter", "Firebase", "GraphQL", "Riverpod"], badges: ["full-stack-dev", "community-leader"], achievements: ["250 Stars"], contributionHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 13)), joinedAt: "2021-03-05" },
  { id: "d8", username: "jamesbrown", displayName: "James Brown", avatar: A+"James", bio: "Backend engineer & API designer.", college: "TU Munich", community: "Developer", organization: "SAP", country: "Germany", city: "Berlin", rank: 8, score: 4320, tier: "Gold", prs: 134, mergedPrs: 108, stars: 3500, followers: 1780, commits: 1080, repos: 24, issues: 45, reviews: 120, streak: 14, languages: ["Java", "TypeScript", "Python", "Kotlin"], techStack: ["Spring Boot", "PostgreSQL", "Kafka", "Docker"], badges: ["top-contributor"], achievements: ["100 Stars"], contributionHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 12)), joinedAt: "2019-11-30" },
  { id: "d9", username: "anagarcia", displayName: "Ana Garcia", avatar: A+"Ana", bio: "Data engineer & open data advocate.", college: "UPC Barcelona", community: "GDG", organization: "Microsoft", country: "Spain", city: "Barcelona", rank: 9, score: 3950, tier: "Gold", prs: 118, mergedPrs: 95, stars: 2800, followers: 1450, commits: 950, repos: 20, issues: 38, reviews: 98, streak: 11, languages: ["Python", "SQL", "R", "Scala"], techStack: ["Spark", "Airflow", "dbt", "Snowflake"], badges: ["ai-builder"], achievements: ["100 Stars"], contributionHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 11)), joinedAt: "2020-09-14" },
  { id: "d10", username: "tomnguyen", displayName: "Tom Nguyen", avatar: A+"Tom", bio: "Cybersecurity researcher & CTF player.", college: "HUST", community: "Student", organization: "GitHub", country: "Vietnam", city: "Hanoi", rank: 10, score: 3580, tier: "Silver", prs: 102, mergedPrs: 82, stars: 2100, followers: 1120, commits: 820, repos: 18, issues: 32, reviews: 85, streak: 9, languages: ["Python", "Go", "Rust", "C"], techStack: ["Burp Suite", "Wireshark", "Metasploit", "Nmap"], badges: ["rising-star"], achievements: ["First PR Merged"], contributionHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 10)), joinedAt: "2022-01-20" },
  { id: "d11", username: "rachellee", displayName: "Rachel Lee", avatar: A+"Rachel", bio: "Full-stack developer building developer tools.", college: "NUS", community: "GDSC", organization: "Stripe", country: "Singapore", city: "Singapore", rank: 11, score: 3210, tier: "Silver", prs: 89, mergedPrs: 72, stars: 1800, followers: 890, commits: 720, repos: 15, issues: 28, reviews: 72, streak: 7, languages: ["TypeScript", "Python", "JavaScript", "Rust"], techStack: ["React", "Node.js", "PostgreSQL", "Redis"], badges: [], achievements: [], contributionHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 9)), joinedAt: "2021-08-15" },
  { id: "d12", username: "chrispatel", displayName: "Chris Patel", avatar: A+"Chris", bio: "Student developer & open source newbie.", college: "IIT Delhi", community: "MLSA", organization: "", country: "India", city: "Delhi", rank: 12, score: 2850, tier: "Bronze", prs: 45, mergedPrs: 32, stars: 800, followers: 340, commits: 380, repos: 8, issues: 18, reviews: 25, streak: 3, languages: ["Python", "JavaScript", "C++"], techStack: ["React", "Flask", "MongoDB"], badges: ["rising-star"], achievements: ["First PR Merged"], contributionHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 6)), joinedAt: "2023-06-01" },
];

export const TIER_THRESHOLDS = [
  { tier: "Bronze" as const, minScore: 0, maxScore: 999, color: "from-amber-700 to-amber-500", textColor: "text-amber-500", bgColor: "bg-amber-900/20" },
  { tier: "Silver" as const, minScore: 1000, maxScore: 2999, color: "from-gray-400 to-gray-300", textColor: "text-gray-300", bgColor: "bg-gray-400/10" },
  { tier: "Gold" as const, minScore: 3000, maxScore: 4999, color: "from-yellow-500 to-amber-400", textColor: "text-yellow-400", bgColor: "bg-yellow-500/10" },
  { tier: "Platinum" as const, minScore: 5000, maxScore: 6999, color: "from-cyan-400 to-blue-400", textColor: "text-cyan-300", bgColor: "bg-cyan-500/10" },
  { tier: "Diamond" as const, minScore: 7000, maxScore: 8999, color: "from-blue-400 to-indigo-500", textColor: "text-blue-300", bgColor: "bg-blue-500/10" },
  { tier: "Elite" as const, minScore: 9000, maxScore: Infinity, color: "from-purple-500 to-pink-500", textColor: "text-purple-300", bgColor: "bg-purple-500/10" },
];

export const COLLEGES: College[] = [
  { id: "c1", name: "MIT", location: "Cambridge, MA", country: "USA", studentCount: 11520, contributorCount: 2840, totalScore: 98500, topContributor: "Alex Chen", topContributorScore: 9850, placementReadiness: 96, innovationScore: 98, communityImpact: 92, departments: ["CS", "EE", "Math", "Physics"], rank: 1, growth: 12, trend: "up" },
  { id: "c2", name: "Stanford University", location: "Stanford, CA", country: "USA", studentCount: 17250, contributorCount: 2560, totalScore: 87200, topContributor: "Sarah Johnson", topContributorScore: 8720, placementReadiness: 95, innovationScore: 97, communityImpact: 90, departments: ["CS", "AI", "EE", "Business"], rank: 2, growth: 8, trend: "up" },
  { id: "c3", name: "IIT Bombay", location: "Mumbai", country: "India", studentCount: 12450, contributorCount: 3210, totalScore: 76500, topContributor: "Priya Sharma", topContributorScore: 7650, placementReadiness: 92, innovationScore: 88, communityImpact: 95, departments: ["CS", "EE", "Mechanical", "Aerospace"], rank: 3, growth: 18, trend: "up" },
  { id: "c4", name: "National University of Singapore", location: "Singapore", country: "Singapore", studentCount: 38200, contributorCount: 1890, totalScore: 65400, topContributor: "Rachel Lee", topContributorScore: 3210, placementReadiness: 90, innovationScore: 85, communityImpact: 82, departments: ["CS", "Engineering", "Business"], rank: 4, growth: 15, trend: "up" },
  { id: "c5", name: "KAIST", location: "Daejeon", country: "South Korea", studentCount: 10400, contributorCount: 1450, totalScore: 52100, topContributor: "David Kim", topContributorScore: 5210, placementReadiness: 88, innovationScore: 92, communityImpact: 75, departments: ["CS", "EE", "AI", "Chemistry"], rank: 5, growth: 10, trend: "up" },
  { id: "c6", name: "University of British Columbia", location: "Vancouver, BC", country: "Canada", studentCount: 65800, contributorCount: 1320, totalScore: 47800, topContributor: "Emma Wilson", topContributorScore: 5890, placementReadiness: 85, innovationScore: 80, communityImpact: 78, departments: ["CS", "Engineering", "Science"], rank: 6, growth: 6, trend: "stable" },
  { id: "c7", name: "TU Munich", location: "Munich", country: "Germany", studentCount: 48200, contributorCount: 1180, totalScore: 43200, topContributor: "James Brown", topContributorScore: 4320, placementReadiness: 88, innovationScore: 82, communityImpact: 72, departments: ["CS", "EE", "Mechanical"], rank: 7, growth: 5, trend: "stable" },
  { id: "c8", name: "IIT Delhi", location: "New Delhi", country: "India", studentCount: 11200, contributorCount: 2340, totalScore: 39800, topContributor: "Chris Patel", topContributorScore: 2850, placementReadiness: 90, innovationScore: 85, communityImpact: 88, departments: ["CS", "EE", "Math", "Physics"], rank: 8, growth: 22, trend: "up" },
  { id: "c9", name: "UNSW Sydney", location: "Sydney", country: "Australia", studentCount: 62300, contributorCount: 980, totalScore: 35800, topContributor: "Lisa Thompson", topContributorScore: 4780, placementReadiness: 82, innovationScore: 76, communityImpact: 70, departments: ["CS", "Engineering", "Business"], rank: 9, growth: 4, trend: "stable" },
  { id: "c10", name: "UPC Barcelona", location: "Barcelona", country: "Spain", studentCount: 30500, contributorCount: 720, totalScore: 28500, topContributor: "Ana Garcia", topContributorScore: 3950, placementReadiness: 78, innovationScore: 72, communityImpact: 65, departments: ["CS", "EE", "Math"], rank: 10, growth: 3, trend: "stable" },
];

export const COMMUNITIES: Community[] = [
  { id: "cm1", name: "MLSA India", type: "MLSA", description: "Microsoft Learn Student Ambassadors - India Chapter", memberCount: 12500, contributorCount: 3420, totalScore: 85200, projects: 156, events: 89, rank: 1, growth: 28, topMembers: ["Priya Sharma", "Chris Patel", "Rohan Gupta"], location: "India", website: "https://studentambassadors.microsoft.com" },
  { id: "cm2", name: "GDSC Stanford", type: "GDSC", description: "Google Developer Student Clubs - Stanford University", memberCount: 2800, contributorCount: 890, totalScore: 52100, projects: 78, events: 45, rank: 2, growth: 15, topMembers: ["Sarah Johnson", "Mike Chen"], location: "Stanford, CA", website: "https://developers.google.com/community/gdsc" },
  { id: "cm3", name: "AWS User Group Bengaluru", type: "AWS User Group", description: "AWS User Group - Bengaluru Chapter", memberCount: 8500, contributorCount: 2100, totalScore: 48500, projects: 92, events: 56, rank: 3, growth: 22, topMembers: ["Priya Sharma", "Arun Kumar"], location: "Bengaluru, India" },
  { id: "cm4", name: "GDG Berlin", type: "GDG", description: "Google Developer Group Berlin", memberCount: 4500, contributorCount: 1200, totalScore: 32100, projects: 45, events: 32, rank: 4, growth: 8, topMembers: ["James Brown", "Lisa Weber"], location: "Berlin, Germany" },
  { id: "cm5", name: "KAI Developer Community", type: "Developer", description: "Korean AI Developer Community", memberCount: 6200, contributorCount: 1800, totalScore: 29800, projects: 34, events: 28, rank: 5, growth: 18, topMembers: ["David Kim", "Min Ji"], location: "Seoul, South Korea" },
  { id: "cm6", name: "Open Source Club - MIT", type: "Open Source", description: "MIT Open Source Club", memberCount: 1200, contributorCount: 680, totalScore: 25400, projects: 56, events: 22, rank: 6, growth: 12, topMembers: ["Alex Chen", "Mike Rodriguez"], location: "Cambridge, MA" },
  { id: "cm7", name: "Sydney Dev Community", type: "Developer", description: "Sydney Developer Community", memberCount: 3800, contributorCount: 950, totalScore: 18500, projects: 28, events: 18, rank: 7, growth: 6, topMembers: ["Lisa Thompson", "James Wilson"], location: "Sydney, Australia" },
  { id: "cm8", name: "Startup Hub Delhi", type: "Startup", description: "Delhi NCR Startup Community", memberCount: 7200, contributorCount: 1500, totalScore: 15800, projects: 89, events: 42, rank: 8, growth: 35, topMembers: ["Chris Patel", "Neha Gupta"], location: "Delhi, India" },
];

export const ORGANIZATIONS: Organization[] = [
  { id: "o1", name: "Google", description: "Organizing the world's information", avatar: A+"Google", memberCount: 450, repoCount: 3200, totalStars: 5420000, totalForks: 1250000, contributorCount: 28400, rank: 1, growth: 12, topRepos: ["TensorFlow", "Kubernetes", "Angular", "Go"], topLanguages: ["Go", "Python", "TypeScript", "C++"] },
  { id: "o2", name: "Microsoft", description: "Empowering every person and organization on the planet", avatar: A+"Microsoft", memberCount: 520, repoCount: 4100, totalStars: 4850000, totalForks: 1120000, contributorCount: 32100, rank: 2, growth: 8, topRepos: ["VS Code", "TypeScript", "Azure SDK", "PowerShell"], topLanguages: ["TypeScript", "C#", "Python", "C++"] },
  { id: "o3", name: "Meta", description: "Building the future of social connection", avatar: A+"Meta", memberCount: 280, repoCount: 1800, totalStars: 3250000, totalForks: 780000, contributorCount: 18500, rank: 3, growth: 5, topRepos: ["React", "PyTorch", "React Native", "GraphQL"], topLanguages: ["JavaScript", "Python", "TypeScript", "C++"] },
  { id: "o4", name: "Amazon", description: "Earth's most customer-centric company", avatar: A+"Amazon", memberCount: 320, repoCount: 1500, totalStars: 2100000, totalForks: 520000, contributorCount: 15200, rank: 4, growth: 10, topRepos: ["AWS SDK", "CDK", "Corretto", "OpenJDK"], topLanguages: ["Java", "Python", "Go", "TypeScript"] },
  { id: "o5", name: "Vercel", description: "Build, deploy, and scale web applications", avatar: A+"Vercel", memberCount: 80, repoCount: 120, totalStars: 1850000, totalForks: 350000, contributorCount: 8500, rank: 5, growth: 25, topRepos: ["Next.js", "Turborepo", "SWR", "Hyper"], topLanguages: ["TypeScript", "JavaScript", "Rust", "Go"] },
  { id: "o6", name: "Netflix", description: "Entertainment on demand", avatar: A+"Netflix", memberCount: 120, repoCount: 450, totalStars: 980000, totalForks: 210000, contributorCount: 5800, rank: 6, growth: 8, topRepos: ["Metaflow", "Zuul", "Atlas", "Hystrix"], topLanguages: ["Java", "Python", "Go", "TypeScript"] },
];

export const HACKATHONS: Hackathon[] = [
  { id: "h1", name: "HackMIT 2026", description: "MIT's premier hackathon", date: "2026-09-15", location: "Cambridge, MA", participantCount: 1200, projectCount: 280, winner: "Team AI Nexus", winnerScore: 980, topTeams: ["AI Nexus", "Blockchain Bros", "Cloud Nine"], rank: 1, type: "In-Person" },
  { id: "h2", name: "Hacktoberfest 2026", description: "Month-long open source celebration", date: "2026-10-01", location: "Global", participantCount: 85000, projectCount: 15000, winner: "Contributor Elite", winnerScore: 2500, topTeams: ["OSS Heroes", "PR Masters", "Code Warriors"], rank: 2, type: "Online" },
  { id: "h3", name: "DevSprint Bengaluru", description: "India's largest developer hackathon", date: "2026-07-20", location: "Bengaluru, India", participantCount: 3500, projectCount: 720, winner: "PayAlpha", winnerScore: 920, topTeams: ["PayAlpha", "HealthStack", "EduFlow"], rank: 3, type: "Hybrid" },
  { id: "h4", name: "AI for Good Hackathon", description: "Building AI solutions for social impact", date: "2026-08-10", location: "San Francisco, CA", participantCount: 800, projectCount: 180, winner: "EcoSense", winnerScore: 950, topTeams: ["EcoSense", "MedAI", "LearnForward"], rank: 4, type: "In-Person" },
  { id: "h5", name: "Global Hack Week", description: "Week-long global virtual hackathon", date: "2026-06-01", location: "Online", participantCount: 12000, projectCount: 2800, winner: "DevChain", winnerScore: 1800, topTeams: ["DevChain", "QuantumLeap", "DataPulse"], rank: 5, type: "Online" },
];

export const BADGES: DevRankBadge[] = [
  { id: "top-contributor", name: "🏆 Top Contributor", description: "Awarded to developers in the global top 100", icon: "trophy", color: "from-amber-400 to-yellow-500", gradient: "from-amber-500/20 to-yellow-500/10", category: "contribution", condition: "Top 100 global rank", unlocked: true, unlockedAt: "2 months ago" },
  { id: "open-source-champion", name: "🚀 Open Source Champion", description: "100+ merged PRs in open source projects", icon: "rocket", color: "from-emerald-400 to-teal-500", gradient: "from-emerald-500/20 to-teal-500/10", category: "contribution", condition: "100+ merged PRs", unlocked: true, unlockedAt: "1 week ago" },
  { id: "ai-builder", name: "🤖 AI Builder", description: "Contributions to AI/ML open source projects", icon: "bot", color: "from-blue-400 to-purple-500", gradient: "from-blue-500/20 to-purple-500/10", category: "skill", condition: "AI/ML project contributions", unlocked: false },
  { id: "full-stack-dev", name: "💻 Full Stack Developer", description: "Versatile developer across frontend & backend", icon: "code", color: "from-indigo-400 to-blue-500", gradient: "from-indigo-500/20 to-blue-500/10", category: "skill", condition: "Frontend + Backend contributions", unlocked: true, unlockedAt: "3 days ago" },
  { id: "community-leader", name: "🌟 Community Leader", description: "Leadership in developer communities", icon: "star", color: "from-purple-400 to-pink-500", gradient: "from-purple-500/20 to-pink-500/10", category: "community", condition: "Community organizer", unlocked: true, unlockedAt: "1 month ago" },
  { id: "hackathon-winner", name: "🏅 Hackathon Winner", description: "Winner of a recognized hackathon", icon: "medal", color: "from-amber-400 to-orange-500", gradient: "from-amber-500/20 to-orange-500/10", category: "hackathon", condition: "Win any hackathon", unlocked: false },
  { id: "student-ambassador", name: "🎓 Student Ambassador", description: "Active student community representative", icon: "graduation", color: "from-sky-400 to-blue-500", gradient: "from-sky-500/20 to-blue-500/10", category: "community", condition: "Student ambassador program", unlocked: true, unlockedAt: "2 weeks ago" },
  { id: "rising-star", name: "🔥 Rising Star", description: "Fastest growing contributor score", icon: "flame", color: "from-red-400 to-orange-500", gradient: "from-red-500/20 to-orange-500/10", category: "achievement", condition: "Top 10% growth rate", unlocked: true, unlockedAt: "5 days ago" },
  { id: "innovation-award", name: "⚡ Innovation Award", description: "Novel and innovative open source contributions", icon: "zap", color: "from-amber-400 to-yellow-500", gradient: "from-amber-500/20 to-yellow-500/10", category: "achievement", condition: "Innovative project recognition", unlocked: false },
  { id: "elite-contributor", name: "👑 Elite Contributor", description: "The highest tier of contribution excellence", icon: "crown", color: "from-violet-400 to-purple-500", gradient: "from-violet-500/20 to-purple-500/10", category: "contribution", condition: "Elite tier status", unlocked: false },
];

export const INSIGHTS: Insight[] = [
  { id: "i1", type: "strength", title: "TypeScript Expertise", description: "Your TypeScript contributions are in the top 5% globally. Consider mentoring others or creating educational content.", score: 95, color: "from-emerald-500 to-teal-500" },
  { id: "i2", type: "strength", title: "PR Success Rate", description: "With 87% of your PRs being merged, you have excellent code quality and communication skills.", score: 87, color: "from-blue-500 to-cyan-500" },
  { id: "i3", type: "weakness", title: "Documentation Contributions", description: "Documentation contributions are below average. Improving docs is a great way to give back to projects you use.", score: 35, color: "from-amber-500 to-orange-500" },
  { id: "i4", type: "weakness", title: "Code Review Participation", description: "Your review-to-PR ratio is 0.4:1. Aim for at least 2:1 to be a well-rounded community member.", score: 42, color: "from-red-500 to-rose-500" },
  { id: "i5", type: "opportunity", title: "Machine Learning Projects", description: "Your Python skills are strong but you haven't contributed to ML projects. There's high demand for ML contributors.", score: 78, color: "from-purple-500 to-pink-500" },
  { id: "i6", type: "opportunity", title: "Rust Ecosystem Growth", description: "Rust adoption is growing 40% YoY. Your systems experience makes you well-positioned to contribute to Rust projects.", score: 72, color: "from-violet-500 to-indigo-500" },
  { id: "i7", type: "recommendation", title: "Focus on Kubernetes", description: "Based on your Go experience, contributing to Kubernetes would leverage your skills and open major career opportunities.", score: 88, color: "from-blue-500 to-indigo-500" },
  { id: "i8", type: "recommendation", title: "Start a Blog", description: "Developers who blog get 3x more opportunities. Share what you've learned about TypeScript and distributed systems.", score: 82, color: "from-emerald-500 to-teal-500" },
];

export const DEFAULT_GITHUB_STATS: GitHubStats = {
  totalCommits: 2840, totalRepos: 87, totalPRs: 342, mergedPRs: 298, prSuccessRate: 87.1,
  totalIssues: 156, issuesClosed: 132, issueResolutionRate: 84.6,
  totalStars: 15200, totalForks: 3200, totalWatchers: 840, totalFollowers: 8430,
  contributionStreak: 45, longestStreak: 62,
  languageDistribution: [
    { language: "TypeScript", percentage: 42, color: "#3178c6" },
    { language: "Rust", percentage: 22, color: "#dea584" },
    { language: "Python", percentage: 18, color: "#3572a5" },
    { language: "Go", percentage: 10, color: "#00add8" },
    { language: "JavaScript", percentage: 8, color: "#f1e05a" },
  ],
  activityHeatmap: Array(365).fill(0).map(() => Math.floor(Math.random() * 25)),
  repoGrowth: [
    { date: "2025-01", count: 45 }, { date: "2025-02", count: 48 }, { date: "2025-03", count: 52 }, { date: "2025-04", count: 55 }, { date: "2025-05", count: 58 }, { date: "2025-06", count: 62 }, { date: "2025-07", count: 65 }, { date: "2025-08", count: 68 }, { date: "2025-09", count: 72 }, { date: "2025-10", count: 75 }, { date: "2025-11", count: 80 }, { date: "2025-12", count: 82 }, { date: "2026-01", count: 84 }, { date: "2026-02", count: 85 }, { date: "2026-03", count: 86 }, { date: "2026-04", count: 86 }, { date: "2026-05", count: 87 }, { date: "2026-06", count: 87 }],
};

export const SCORE_WEIGHTS = {
  commits: 1.5, mergedPRs: 3.0, issuesClosed: 1.0, reposMaintained: 2.5,
  starsEarned: 0.5, followers: 0.3, hackathonPoints: 2.0, communityPoints: 1.5, learningAchievements: 1.0,
};

export const ALL_LANGUAGES = ["TypeScript", "JavaScript", "Python", "Rust", "Go", "Java", "C++", "Ruby", "Swift", "Kotlin", "Dart", "C", "C#", "PHP", "Scala", "R", "Shell", "HCL", "SQL"];
export const ALL_COUNTRIES = ["USA", "India", "Canada", "UK", "Germany", "Singapore", "South Korea", "Australia", "Spain", "Vietnam", "Japan", "Brazil", "France", "Netherlands", "Sweden"];
